const KEY = "cappie.v1";
const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

const LIMB_OPTIONS = [
  { id: "left_hand", label: "Left hand / partial hand", group: "upper" },
  { id: "right_hand", label: "Right hand / partial hand", group: "upper" },
  { id: "left_below_elbow", label: "Left below elbow", group: "upper" },
  { id: "right_below_elbow", label: "Right below elbow", group: "upper" },
  { id: "left_above_elbow", label: "Left above elbow", group: "upper" },
  { id: "right_above_elbow", label: "Right above elbow", group: "upper" },
  { id: "left_below_knee", label: "Left below knee", group: "lower" },
  { id: "right_below_knee", label: "Right below knee", group: "lower" },
  { id: "left_above_knee", label: "Left above knee", group: "lower" },
  { id: "right_above_knee", label: "Right above knee", group: "lower" }
];

const EQUIPMENT_OPTIONS = [
  { id: "gripper", label: "Hand gripper" },
  { id: "pinch_block", label: "Pinch block" },
  { id: "putty", label: "Therapy putty" },
  { id: "loop_band", label: "Loop band" },
  { id: "tube_band", label: "Tube band / straps" },
  { id: "door_anchor", label: "Doorway anchor" },
  { id: "chair", label: "Chair" },
  { id: "mat", label: "Mat / bed" }
];

const THEMES = [
  { id: "clay", label: "Clay" },
  { id: "forest", label: "Forest" },
  { id: "ink", label: "Ink" },
  { id: "dusk", label: "Dusk" }
];

const WALLS = [
  { id: "linen", label: "Linen" },
  { id: "sand", label: "Sand" },
  { id: "slate", label: "Slate" },
  { id: "meadow", label: "Meadow" }
];

const SRC = "Heleen Groenewald · 4 Sep 2026";

const EXERCISES = [
  { id: "crush_grip", name: "Crush grip", category: "grip", tag: "grip", equipment: ["gripper"], position: "either", metric: "reps", defaultSets: 3, defaultValue: 8, cue: "Close the gripper fully. Pause. Open with control.", description: "A closing-strength drill for the hand you can still use.", how: ["Hold the gripper in a comfortable handshake grip.", "Close it fully. Pause one second.", "Open with control. Do not let it snap."], adaptation: "Use the sound hand, or the residual if you can hold the trainer." },
  { id: "pinch_hold", name: "Pinch hold", category: "grip", tag: "grip", equipment: ["pinch_block"], position: "either", metric: "seconds", defaultSets: 3, defaultValue: 20, cue: "Pinch and hold without shrugging the shoulder.", description: "Thumb-to-finger pinch endurance.", how: ["Pinch the block between thumb and fingers.", "Hold still. Shoulder stays down.", "Put it down when the pinch slips."], adaptation: "Shorten the hold if the pinch slips." },
  { id: "putty_squeeze", name: "Putty squeeze", category: "grip", tag: "grip", equipment: ["putty"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 12, cue: "Press into the putty, then open the hand fully.", description: "Soft-to-firm squeeze to open and close the hand through a full range.", how: ["Sit. Putty in the palm.", "Squeeze. Pause.", "Open the hand fully before the next squeeze."], adaptation: "Softer putty first. Stop if residual skin blanches." },
  { id: "putty_pinch", name: "Putty pinch", category: "grip", tag: "grip", equipment: ["putty"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 10, cue: "Thumb to each finger in turn through the putty.", description: "Thumb opposition through putty, finger by finger.", how: ["Roll a small ball of putty.", "Pinch thumb to index, then middle, ring, little.", "Skip any finger that is not there."], adaptation: "Skip fingers that are not there." },
  { id: "finger_ext", name: "Finger extension band", category: "grip", tag: "grip", equipment: ["loop_band"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 12, cue: "Light loop over the fingers. Open against the band.", description: "Opens the fingers against a light loop — the opposite of a squeeze.", how: ["Light loop over the fingers.", "Open the fingers against the band.", "Return slow."], adaptation: "Needs a usable hand." },
  { id: "seated_row", name: "Seated band row", category: "band", tag: "upper", equipment: ["tube_band", "loop_band", "chair"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 10, cue: "Sit tall. Pull elbows back. Pause. Return slow.", description: "Upper-back row from a chair.", how: ["Sit tall. Band in front or around the feet.", "Pull elbows back. Pause.", "Return slow. Do not shrug."], adaptation: "Strap a handle to a residual limb if a grip is not available." },
  { id: "chest_press", name: "Seated chest press", category: "band", tag: "upper", equipment: ["tube_band", "loop_band"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 10, cue: "Band behind the back or on an anchor. Press forward.", description: "Press the arms forward against a band.", how: ["Band behind the back or on an anchor.", "Press forward to straight elbows.", "Return without collapsing the chest."], adaptation: "One-arm variant is fine." },
  { id: "ext_rot", name: "Shoulder external rotation", category: "band", tag: "upper", equipment: ["loop_band", "tube_band"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 12, cue: "Elbow at the side. Rotate the forearm out. Light band.", description: "Rotator-cuff drill with a light band.", how: ["Elbow glued to the side.", "Rotate the forearm out.", "Return slow. Light band only."], adaptation: "Do the sound side if needed." },
  { id: "pull_apart", name: "Band pull-apart", category: "band", tag: "upper", equipment: ["loop_band", "tube_band"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 12, cue: "Arms long. Pull the band apart until it meets the chest line.", description: "Opens the chest and upper back.", how: ["Hold the band at chest height, arms long.", "Pull apart until it meets the chest line.", "Return slow."], adaptation: "Loop around residual limb and sound hand." },
  { id: "hip_abd", name: "Hip abduction (band)", category: "band", tag: "lower", equipment: ["loop_band"], position: "either", metric: "reps", defaultSets: 3, defaultValue: 10, cue: "Loop above the knees or residual limb. Press out.", description: "Press the thighs out against a loop band.", how: ["Loop above the knees or residual.", "Press out. Pause.", "Return without collapsing."], adaptation: "Seated first." },
  { id: "hip_ext", name: "Hip extension (band)", category: "band", tag: "lower", equipment: ["tube_band", "door_anchor"], position: "standing", metric: "reps", defaultSets: 3, defaultValue: 10, cue: "Anchor in front. Press the limb back without arching.", description: "Press the limb back against a front anchor.", how: ["Anchor in front. Hold a chair if you need it.", "Press the limb straight back.", "Do not arch the low back."], adaptation: "Hold a chair if you need it." },
  { id: "core_twist", name: "Seated core twist", category: "band", tag: "general", equipment: ["chair"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 8, cue: "Hands at the chest. Rotate from the ribs, not the neck.", description: "Rotation from the ribs while you sit tall.", how: ["Sit tall. Hands at the chest.", "Rotate from the ribs, not the neck.", "Change sides."], adaptation: "Add a light band if you have one." },
  { id: "residual_iso", name: "Residual-limb isometric", category: "band", tag: "general", equipment: ["tube_band", "loop_band"], position: "seated", metric: "seconds", defaultSets: 3, defaultValue: 15, cue: "Press the residual limb into a band or stable object. Hold.", description: "A quiet press of the residual into a band or object. No swing.", how: ["Sit. Residual against a band or stable object.", "Press and hold.", "Breathe. Stop on sharp pain."], adaptation: "Intensity comes from your clinician. Stop on sharp pain." },

  { id: "ankle_pumps", name: "Ankle pumps", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 15, source: SRC, photos: ["photos/ankle-pumps.jpg"], cue: "On your back. Point the sound foot up, then down.", description: "A circulation and ankle-mobility drill for the sound side.", how: ["Lie on your back, residual supported if needed.", "Point the sound foot down, then pull the toes toward you.", "Smooth, not rushed. That is one rep."], adaptation: "Sound side only if the residual has no ankle." },
  { id: "quad_iso", name: "Quadriceps isometric", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "seconds", defaultSets: 3, defaultValue: 8, source: SRC, photos: ["photos/quad-iso.jpg"], cue: "On your back. Support the residual with a pillow. Press the back of the knee down toward the floor.", description: "A still hold that wakes the thigh without bending the knee.", how: ["Lie on your back. Pillow under the residual.", "Press the back of the knee down into the support.", "Hold. Thigh should firm. Breathe.", "Ease off. Rest, then repeat."], adaptation: "Stop if the residual blanches or stings." },
  { id: "knee_ext_arom", name: "Knee extension AROM", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 10, source: SRC, photos: ["photos/knee-ext-arom.jpg"], cue: "On your back. Support the residual as shown. Straighten the knee.", description: "Active straightening of the residual knee through the range you have.", how: ["Lie on your back. Residual supported as in the photo.", "Straighten the knee. Pause when it is as straight as it will go.", "Lower with control. Small range first."], adaptation: "Small range first." },
  { id: "supine_crunch", name: "Supine crunch, hands to knees", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, photos: ["photos/supine-crunch.jpg"], cue: "On your back, hands at the knees. Crunch and reach toward the knees.", description: "A small sit-up. Reach the hands toward the knees. The neck stays long.", how: ["Lie on your back. Hands toward the knees.", "Curl the ribs toward the thighs. Reach.", "Lower slow. Do not yank the neck."], adaptation: "Keep the neck long." },
  { id: "oblique_crunch", name: "Oblique crunch", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, photos: ["photos/oblique-crunch.jpg"], cue: "On your back, sound leg bent, hands to head. Crunch and twist, elbow toward knee.", description: "A twist crunch. The work is in the side of the waist, not the neck.", how: ["Lie on your back. Sound knee bent. Hands beside the head.", "Curl and twist. Elbow toward the knee.", "Lower. Change sides if that is in the plan."], adaptation: "Move from the ribs." },
  { id: "dead_bug", name: "Dead bug", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, photos: ["photos/dead-bug-start.jpg", "photos/dead-bug-move.jpg"], cue: "On your back. Opposite arm and leg move. The low back stays quiet.", description: "A core-control drill. You lie on your back and move the opposite arm and leg while the trunk stays still. The point is a quiet lower back, not a big kick.", how: ["Lie on your back. Residual supported on the bed.", "Lift the sound leg so the thigh is vertical, knee bent. Reach both arms straight up over the chest. This is the start — first photo.", "Press the lower back gently into the mat. Take a breath in. The ribs stay heavy.", "Breathe out. Lower the opposite arm overhead and the sound foot toward the floor, only as far as the back stays flat. This is the move — second photo.", "Return to the start without letting the back arch. That is one rep.", "If the back lifts off the mat, shorten the movement. The residual limb can stay on the bed as an anchor.", "Do not swing. Slow down. Quality over range."], adaptation: "Keep the low back quiet. Shorten the movement if it arches." },
  { id: "hamstring_stretch", name: "Hamstring stretch", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "seconds", defaultSets: 2, defaultValue: 20, source: SRC, photos: ["photos/hamstring-stretch.jpg"], cue: "On your back. Draw the sound leg up until you feel a stretch. Residual stays flat.", description: "A still stretch of the sound hamstring. No bouncing.", how: ["Lie on your back, residual flat on the bed.", "Lift the sound leg. Hold behind the thigh.", "Straighten the knee until you feel a stretch. Pointing the toe toward the floor increases it.", "Hold. Breathe. Do not bounce."], adaptation: "Do not bounce." },
  { id: "prone_elbows", name: "Prone on elbows", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "seconds", defaultSets: 2, defaultValue: 20, source: SRC, photos: ["photos/prone-elbows.jpg"], cue: "Lie on your front, propped on the elbows.", description: "A hold on the front of the body, propped on the elbows. Builds trunk endurance.", how: ["Roll onto your front.", "Prop on the elbows. Shoulders over the elbows.", "Breathe. Residual comfortable on the bed.", "Come down if the residual protests."], adaptation: "Come down if the residual protests." },
  { id: "hip_ext_arom", name: "Hip extension AROM", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 10, source: SRC, photos: ["photos/hip-ext-arom.jpg"], cue: "On your front. Support the residual. Lift it straight up.", description: "On your front, lift the residual straight up. Small, controlled.", how: ["Lie on your front. Residual supported as shown.", "Lift the residual straight up. Small lift.", "Lower. No low-back pinch."], adaptation: "Small lift. No low-back pinch." },
  { id: "hip_ext_bent", name: "Hip extension, bent knee", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, photos: ["photos/hip-ext-bent.jpg"], cue: "On your stomach, knee bent. Lead with the heel and lift.", description: "Same lift as hip extension, with the residual knee bent. Heel leads.", how: ["Lie on your stomach. Bend the residual knee.", "Lead with the heel. Lift.", "Higher only if you stay in control. Stop on sharp pain."], adaptation: "Stop on sharp pain." },
  { id: "bridge_sound", name: "Bridge, sound leg", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, photos: ["photos/bridge-sound.jpg"], cue: "On your back, sound leg bent, foot flat. Lift the hips.", description: "A single-leg style bridge on the sound side. Residual rests.", how: ["Lie on your back. Sound foot flat, knee bent.", "Press through the sound heel. Lift the hips.", "Lower with control."], adaptation: "Press through the sound heel." },
  { id: "bridge_band", name: "Bridge, arms at side (band)", category: "bka", tag: "bka", equipment: ["loop_band", "mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, photos: ["photos/bridge-band.jpg"], cue: "Band as shown. On your back, sound leg bent. Lift the hips.", description: "Bridge with a light loop band for extra hip work.", how: ["Band on as shown. Lie on your back.", "Sound foot flat. Arms at your sides.", "Lift the hips. Light band first."], adaptation: "Light band first." },
  { id: "hip_abd_supine", name: "Hip abduction, on back", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 10, source: SRC, photos: ["photos/hip-abd-supine.jpg"], cue: "Flat on your back. Lift the residual straight out to the side.", description: "Slide or lift the residual out to the side while you stay on your back.", how: ["Lie flat on your back.", "Take the residual straight out to the side.", "Keep the pelvis still. Return."], adaptation: "Keep the pelvis still." },
  { id: "hip_abd_band_lie", name: "Hip abduction (band, lying)", category: "bka", tag: "bka", equipment: ["loop_band", "mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 10, source: SRC, photos: ["photos/hip-abd-band-lie.jpg"], cue: "Band on as shown. Flat on your back. Lift the residual out against the band.", description: "Same side-lift as hip abduction, with a loop band for load.", how: ["Band on as shown.", "Lie on your back.", "Lift the residual out against the band. Stop if the residual skin rolls."], adaptation: "Stop if the residual skin rolls." },
  { id: "hip_add_iso", name: "Hip adduction isometric", category: "bka", tag: "bka", equipment: ["mat"], position: "seated", metric: "seconds", defaultSets: 3, defaultValue: 8, source: SRC, photos: ["photos/hip-add-iso.jpg"], cue: "Sit with legs long. Towel between the thighs. Press the legs together.", description: "A gentle inner-thigh press. Nothing moves.", how: ["Sit with the legs long.", "Towel or pillow between the thighs.", "Press the legs together. Hold. Gentle."], adaptation: "Gentle press." },
  { id: "sidelying", name: "Sidelying", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "seconds", defaultSets: 2, defaultValue: 30, source: SRC, photos: ["photos/sidelying.jpg"], cue: "Lie on your side. Breathe. Change sides if it is a hold.", description: "A rest position and a start position for the side-lying hip work.", how: ["Lie on your side. Head supported.", "Breathe. Residual comfortable.", "Pillow between the limbs if needed. Change sides when the hold is done."], adaptation: "Pillow between limbs if needed." },
  { id: "hip_abd_arom", name: "Hip abduction AROM", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 10, source: SRC, photos: ["photos/hip-abd-arom.jpg"], cue: "Lie on your side. Lift the residual straight up.", description: "On your side, lift the residual straight toward the ceiling.", how: ["Lie on your side. Body in a straight line.", "Lift the residual straight up.", "Do not roll the pelvis back. Lower slow."], adaptation: "Do not roll the pelvis back." },
  { id: "hip_flex_ext_arom", name: "Hip flexion + extension AROM", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, photos: ["photos/hip-flex-ext-arom.jpg"], cue: "Lie on your side. Send the residual forward, then press it straight back.", description: "On your side, swing the residual forward, then straight back. Slow.", how: ["Lie on your side.", "Send the residual forward.", "Then press it straight back. Stay on your side. Slow."], adaptation: "Slow. Stay on your side." },
  { id: "prone_lying", name: "Prone lying", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "seconds", defaultSets: 1, defaultValue: 60, source: SRC, photos: ["photos/prone-lying.jpg"], cue: "Lie on your front. Quiet breathing.", description: "A still lie on the front. Helps hip extension range and comfort.", how: ["Lie on your front. Head turned to a comfortable side.", "Quiet breathing. Residual relaxed.", "Come off if the residual throbs."], adaptation: "Come off if the residual throbs." },
  { id: "lie_to_sit", name: "Transfer, lie to sit", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 4, source: SRC, photos: ["photos/lie-to-sit.jpg"], cue: "Roll onto your side. Come up onto an elbow. Press up with the arms.", description: "The bed-to-sit transfer, broken into three pictures: side-lying, onto the elbow, then sitting.", how: ["Start on your back.", "Roll onto your side, facing the edge.", "Come up onto an elbow.", "Press up with the arms to sit. Use the sound side to help.", "Reverse to lie back down. That is one rep."], adaptation: "Use the sound side to help." },
  { id: "chair_dip", name: "Chair dip", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "reps", defaultSets: 2, defaultValue: 6, source: SRC, photos: ["photos/chair-dip.jpg"], cue: "Hold the armrests. Press and lift yourself above the chair.", description: "Press through the armrests to lift the body. Feet stay light.", how: ["Sit. Hands on the armrests.", "Press and lift yourself above the seat.", "Lower with control. Skip if the shoulders complain."], adaptation: "Feet stay light. Skip if the shoulders complain." },
  { id: "trunk_rot_seated", name: "Lower trunk rotation", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, photos: ["photos/trunk-rot-seated.jpg"], cue: "Sit tall, arms crossed. Twist to one side, then the other.", description: "Seated twist. Arms crossed. The pelvis stays on the chair.", how: ["Sit tall. Arms crossed.", "Twist to one side. Pause.", "Twist to the other. Pull a little further with the arms only if it stays easy."], adaptation: "Use the arms to pull a little further only if it stays easy." },
  { id: "lateral_shift", name: "Lateral weight shift", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, photos: ["photos/lateral-shift.jpg"], cue: "Sit tall. Lean to one side, then the other.", description: "Shift weight from one sit-bone to the other without collapsing.", how: ["Sit tall.", "Lean to one side. Pause.", "Lean to the other. Keep both sit-bones honest."], adaptation: "Keep both sit-bones honest." },
  { id: "chair_reach", name: "Balance, lateral reach", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, photos: ["photos/chair-reach.jpg"], cue: "Sit in the chair. Reach to one side, then the other.", description: "A seated reach that challenges balance. Hold the chair if you need it.", how: ["Sit in the chair.", "Reach to one side. Pause.", "Reach to the other. Hold the chair if you need it."], adaptation: "Hold the chair if you need it." },
  { id: "trunk_flex_stretch", name: "Trunk forward flexion stretch", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "seconds", defaultSets: 2, defaultValue: 20, source: SRC, photos: ["photos/trunk-flex-stretch.jpg"], cue: "Sit in the chair. Hang the trunk toward the ground.", description: "A forward hang from the chair. Come up slow.", how: ["Sit in the chair.", "Hang the trunk toward the ground.", "Breathe. Come up slow."], adaptation: "Come up slow." },
  { id: "trunk_side_stretch", name: "Trunk side flexion stretch", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "seconds", defaultSets: 2, defaultValue: 15, source: SRC, photos: ["photos/trunk-side-stretch.jpg"], cue: "Sit in the chair. Hang the trunk toward the ground and to one side.", description: "Forward hang, then take it to one side. Change sides.", how: ["Sit in the chair.", "Hang forward, then to one side.", "Breathe. Change sides. No pain into the residual."], adaptation: "No pain into the residual." },
  { id: "hip_flex_ext_stand", name: "Hip flexion + extension, supported", category: "bka", tag: "bka", equipment: ["chair"], position: "standing", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, photos: ["photos/hip-flex-ext-stand.jpg"], cue: "Stand on the sound leg. Hold the chair. Residual forward, then straight back.", description: "Standing, hold the chair. Residual swings forward, then straight back.", how: ["Stand on the sound leg. Hold the chair.", "Lift the residual forward.", "Then swing it straight back. Small range. Stay tall."], adaptation: "Small range. Stay tall." },
  { id: "hip_abd_stand", name: "Hip abduction, supported", category: "bka", tag: "bka", equipment: ["chair"], position: "standing", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, photos: ["photos/hip-abd-stand.jpg"], cue: "Stand on the sound leg. Hold the chair. Residual straight out to the side.", description: "Standing side-lift of the residual. Trunk stays upright.", how: ["Stand on the sound leg. Hold the chair.", "Lift the residual straight out to the side.", "Do not lean the trunk away. Lower."], adaptation: "Do not lean the trunk away." },
  { id: "sit_to_stand", name: "Sit to stand (table)", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "reps", defaultSets: 2, defaultValue: 6, source: SRC, photos: ["photos/sit-to-stand-1.jpg", "photos/sit-to-stand-2.jpg", "photos/sit-to-stand-3.jpg"], cue: "Scoot forward. Hands on the table. Lean, knees over toes, stand.", description: "The sit-to-stand from a chair using the table. Three photos: sit, lean, stand.", how: ["Scoot forward on the chair. Hands on the table.", "Lean the trunk a little forward. Knees over toes.", "Press to stand. Pause.", "Sit back with control. That is one rep."], adaptation: "Use the table. Sit back with control." }
];

const SKIP = [
  { id: "pain", label: "Pain" },
  { id: "fatigue", label: "Fatigue" },
  { id: "no_kit", label: "No kit" },
  { id: "time", label: "No time" },
  { id: "other", label: "Other" }
];

const TUTORIAL = [
  { title: "Today", body: "This is home. Start a session on a training day, or skip and tell Cappie why. Night mode sits at the top so the screen is easy in the evening." },
  { title: "A session", body: "Each exercise has a photo, a plain-language how-to, a timer, and set counters. Mark a set done when you finish it. Photos are from Heleen’s sheets — tap one to open it larger." },
  { title: "Plan", body: "Turn exercises on or off. Change sets and reps. Below-knee unlocks the chair and mat program." },
  { title: "Stats", body: "See how many exercises you logged each day, and whether each movement improved or declined over the week or month." },
  { title: "Settings", body: "Theme, wallpaper, one-handed mode, and this tutorial live here. Changes save on this phone and to your cloud account. Replay the tutorial any time." }
];

export { KEY, DAYS, LIMB_OPTIONS, EQUIPMENT_OPTIONS, THEMES, WALLS, EXERCISES, SKIP, TUTORIAL };
