const KEY = "cappie.v1";
const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

const LIMB_OPTIONS = [
  { id: "left_hand", label: "Left hand / partial hand", group: "upper" },
  { id: "right_hand", label: "Right hand / partial hand", group: "upper" },
  { id: "left_below_elbow", label: "Left below elbow", group: "upper" },
  { id: "right_below_elbow", label: "Right below elbow", group: "upper" },
  { id: "left_above_elbow", label: "Left above elbow", group: "upper" },
  { id: "right_above_elbow", label: "Right above elbow", group: "upper" },
  { id: "left_below_knee", label: "Left below knee", group: "lower" },
  { id: "right_below_knee", label: "Right below knee", group: "lower" },
  { id: "left_above_knee", label: "Left above knee", group: "lower" },
  { id: "right_above_knee", label: "Right above knee", group: "lower" }
];

const EQUIPMENT_OPTIONS = [
  { id: "gripper", label: "Hand gripper" },
  { id: "pinch_block", label: "Pinch block" },
  { id: "putty", label: "Therapy putty" },
  { id: "loop_band", label: "Loop band" },
  { id: "tube_band", label: "Tube band / straps" },
  { id: "door_anchor", label: "Doorway anchor" },
  { id: "chair", label: "Chair" },
  { id: "mat", label: "Mat / bed" }
];

const THEMES = [
  { id: "clay", label: "Clay" },
  { id: "forest", label: "Forest" },
  { id: "ink", label: "Ink" },
  { id: "dusk", label: "Dusk" }
];

const WALLS = [
  { id: "linen", label: "Linen" },
  { id: "sand", label: "Sand" },
  { id: "slate", label: "Slate" },
  { id: "meadow", label: "Meadow" }
];

const SRC = "Heleen Groenewald · 4 Sep 2026";

const EXERCISES = [
  { id: "crush_grip", name: "Crush grip", category: "grip", tag: "grip", equipment: ["gripper"], position: "either", metric: "reps", defaultSets: 3, defaultValue: 8, cue: "Close the gripper fully. Pause. Open with control.", description: "A power-grip drill for the hand you can still use. Full closure, then a slow open — the same pattern used in hand therapy for crush strength after partial-hand or contralateral work.", how: ["Sit. Shoulder down, wrist straight.", "Hold the gripper in a handshake grip. If the residual cannot close it, use the sound hand.", "Close until the handles meet. Pause one second.", "Open with control. Do not let the spring snap."], adaptation: "Sound hand, or residual if it can hold the trainer. Stop if residual skin blanches." },
  { id: "pinch_hold", name: "Pinch hold", category: "grip", tag: "grip", equipment: ["pinch_block"], position: "either", metric: "seconds", defaultSets: 3, defaultValue: 20, cue: "Pinch and hold without shrugging the shoulder.", description: "Thumb-to-finger pinch endurance. Key pinch (thumb to the side of the index) is the one used to turn a key or hold a plate — the pinch most often trained after hand loss on the other side.", how: ["Pinch the block between thumb and the side of the index, or pad-to-pad if that is what you have.", "Hold still. Wrist neutral. Shoulder stays down.", "Put it down when the pinch slips, not when the shoulder hikes."], adaptation: "Shorten the hold if the pinch slips. Skip any missing digit." },
  { id: "putty_squeeze", name: "Putty squeeze", category: "grip", tag: "grip", equipment: ["putty"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 12, cue: "Press into the putty, then open the hand fully.", description: "Mass grip through putty, as in NHS hand-therapy putty programmes. The open after each squeeze matters — it stops the fingers living in a flexed fist.", how: ["Sit. Roll the putty into a ball in the palm.", "Squeeze with all fingers you have. Pause.", "Open the hand fully before the next squeeze.", "Start soft. Move to firmer putty only when the open is easy."], adaptation: "Softer putty first. Stop if residual skin blanches." },
  { id: "putty_pinch", name: "Putty pinch", category: "grip", tag: "grip", equipment: ["putty"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 10, cue: "Thumb to each finger in turn through the putty.", description: "Thumb opposition through putty — tip pinch then pad pinch, finger by finger. The pattern used to rebuild the fine pinch needed for buttons and zips.", how: ["Roll a small ball of putty.", "Pinch thumb to index, then middle, ring, little.", "Make a small O with thumb and finger if those digits are there.", "Skip any finger that is not there. Do not twist the wrist to cheat."], adaptation: "Skip fingers that are not there." },
  { id: "finger_ext", name: "Finger extension band", category: "grip", tag: "grip", equipment: ["loop_band"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 12, cue: "Light loop over the fingers. Open against the band.", description: "The opposite of a squeeze. Opening against a light loop trains the finger extensors so the hand does not stay clawed — standard after grip-heavy work or partial-hand use.", how: ["Light loop over the fingers, below the knuckles.", "Open the fingers against the band.", "Return slow. Wrist stays straight."], adaptation: "Needs a usable hand. Light band only." },
  { id: "seated_row", name: "Seated band row", category: "band", tag: "upper", equipment: ["tube_band", "loop_band", "chair"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 10, cue: "Sit tall. Pull elbows back. Pause. Return slow.", description: "Upper-back row from a chair. After limb loss the remaining shoulder and trunk take more of the day — this drill keeps the shoulder blades working without standing.", how: ["Sit tall, feet or residual supported so you do not slide.", "Band in front, or looped around the feet / residual.", "Pull elbows back. Pause. Shoulder blades toward the spine.", "Return slow. Do not shrug."], adaptation: "Strap a handle to a residual limb if a grip is not available. One-arm row is fine." },
  { id: "chest_press", name: "Seated chest press", category: "band", tag: "upper", equipment: ["tube_band", "loop_band"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 10, cue: "Band behind the back or on an anchor. Press forward.", description: "Press the arms forward against a band. Builds the push used to come up from a chair or bed.", how: ["Band behind the back or on an anchor.", "Press forward to straight elbows without locking hard.", "Return without collapsing the chest."], adaptation: "One-arm variant is fine. Residual can wear a strap." },
  { id: "ext_rot", name: "Shoulder external rotation", category: "band", tag: "upper", equipment: ["loop_band", "tube_band"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 12, cue: "Elbow at the side. Rotate the forearm out. Light band.", description: "Rotator-cuff drill. Amputee programmes keep this light — the cuff is easy to irritate when the other arm is doing extra work.", how: ["Elbow glued to the side, as if holding a folded towel there.", "Rotate the forearm out.", "Return slow. Light band only."], adaptation: "Do the sound side if needed. Stop on sharp shoulder pain." },
  { id: "pull_apart", name: "Band pull-apart", category: "band", tag: "upper", equipment: ["loop_band", "tube_band"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 12, cue: "Arms long. Pull the band apart until it meets the chest line.", description: "Opens the chest and upper back. Useful when a lot of the day is spent sitting or propelling.", how: ["Hold the band at chest height, arms long.", "Pull apart until it meets the chest line.", "Return slow. Ribs stay quiet."], adaptation: "Loop around residual limb and sound hand." },
  { id: "hip_abd", name: "Hip abduction (band)", category: "band", tag: "lower", equipment: ["loop_band"], position: "either", metric: "reps", defaultSets: 3, defaultValue: 10, cue: "Loop above the knees or residual limb. Press out.", description: "Press the thighs out against a loop. Hip abductors keep the pelvis level in walking and in standing on the sound leg — a focus of every BKA strengthening sheet.", how: ["Loop above the knees, or as low on the residual as is comfortable.", "Press out. Pause. Kneecaps stay facing forward.", "Return without collapsing."], adaptation: "Seated first. Stop if the residual skin rolls in the band." },
  { id: "hip_ext", name: "Hip extension (band)", category: "band", tag: "lower", equipment: ["tube_band", "door_anchor"], position: "standing", metric: "reps", defaultSets: 3, defaultValue: 10, cue: "Anchor in front. Press the limb back without arching.", description: "Press the limb back against a front anchor. Hip extensors (glutes) are the muscles that stop the hip staying bent after weeks in a chair.", how: ["Anchor in front. Hold a chair if you need it.", "Stand tall on the sound leg.", "Press the residual (or sound limb) straight back.", "Do not arch the low back. Squeeze the buttock to lift, not the spine."], adaptation: "Hold a chair. Small range first." },
  { id: "core_twist", name: "Seated core twist", category: "band", tag: "general", equipment: ["chair"], position: "seated", metric: "reps", defaultSets: 3, defaultValue: 8, cue: "Hands at the chest. Rotate from the ribs, not the neck.", description: "Rotation from the ribs while you sit tall. Core control is what lets an amputee move a limb without the trunk falling into the hole.", how: ["Sit tall. Both sit-bones on the chair. Hands at the chest.", "Rotate from the ribs, not the neck.", "Pause. Change sides. Pelvis stays on the seat."], adaptation: "Add a light band if you have one." },
  { id: "residual_iso", name: "Residual-limb isometric", category: "band", tag: "general", equipment: ["tube_band", "loop_band"], position: "seated", metric: "seconds", defaultSets: 3, defaultValue: 15, cue: "Press the residual limb into a band or stable object. Hold.", description: "A quiet press of the residual into a band or object. No swing. Used to keep the residual musculature working without shearing the skin.", how: ["Sit. Residual against a band or a stable object (bed rail, cushioned chair leg).", "Press and hold. Breathe.", "Ease off. The skin should not crawl on the support."], adaptation: "Intensity comes from your clinician. Stop on sharp pain or blanching." },

  { id: "ankle_pumps", name: "Ankle pumps", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 15, source: SRC, cue: "On your back. Point the sound foot down, then pull the toes toward you.", description: "A circulation and ankle-mobility drill for the sound side. After a below-knee amputation the remaining foot does more standing — pumps keep the calf moving and the ankle from stiffening into a point.", how: ["Lie on your back. Residual supported on the bed, knee as straight as it will go.", "Point the sound foot down, as if pressing a pedal.", "Pull the toes toward you. That is one rep.", "Smooth, not rushed. Do both directions fully."], adaptation: "Sound side only if the residual has no ankle. Stop if the residual throbs when you fidget." },
  { id: "quad_iso", name: "Quadriceps isometric", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "seconds", defaultSets: 3, defaultValue: 8, source: SRC, cue: "On your back. Towel under the residual. Press the back of the knee down.", description: "A still hold that wakes the thigh without needing a big bend. Published BKA programmes (Saskatchewan, Singapore General, MyHealth Alberta) all start here: tighten the top of the thigh, push the residual down, hold about five seconds.", how: ["Lie on your back. Residual as straight as it will go.", "A small towel or pillow under the residual, behind the knee or calf.", "Press the back of the knee down into the support. The thigh should firm.", "Hold. Breathe. Ease off, rest, repeat.", "You can do the sound side the same way."], adaptation: "Stop if the residual blanches or stings. Do not hold the breath." },
  { id: "knee_ext_arom", name: "Knee extension AROM", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 10, source: SRC, cue: "On your back. Towel under the residual knee. Straighten it.", description: "Active straightening of the residual knee over a roll — the ‘inner-range quads’ drill on every BKA sheet. A bent residual knee that never fully straightens makes a socket and a step much harder.", how: ["Lie on your back. Rolled towel under the residual knee.", "Straighten the knee so the residual lifts. Move slowly.", "Hold about five seconds when it is as straight as it will go.", "Lower with control. Small range first."], adaptation: "Small range first. Keep the hips flat on the bed." },
  { id: "supine_crunch", name: "Supine crunch, hands to knees", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, cue: "On your back, hands toward the knees. Curl the ribs, reach.", description: "A small sit-up used in BKA core work. The neck stays long. The point is to lift the shoulder blades, not to yank the head.", how: ["Lie on your back. Residual supported. Sound knee bent if that is more comfortable.", "Reach both hands toward the knees.", "Curl the ribs toward the thighs. Shoulder blades just off the bed.", "Lower slow. Do not pull on the neck."], adaptation: "Keep the neck long. Stop if the residual jumps off the bed — that is the hip taking over." },
  { id: "oblique_crunch", name: "Oblique crunch", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, cue: "On your back, sound leg bent. Curl and twist, elbow toward knee.", description: "A twist crunch. After amputation the trunk often leans toward the residual. This drill trains the side wall so sitting and reaching stay even.", how: ["Lie on your back. Sound knee bent. Hands beside the head — do not pull the head.", "Curl and twist. Elbow toward the sound knee.", "Lower. Change sides if that is in the plan.", "The work is in the waist, not the neck."], adaptation: "Move from the ribs. Residual stays heavy on the bed." },
  { id: "dead_bug", name: "Dead bug", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, cue: "On your back. Opposite arm and sound leg move. The low back stays quiet.", description: "A core-control drill used for lumbopelvic stability. You lie on your back and move the opposite arm and the sound leg while the trunk stays still. After a BKA the residual is the anchor. The point is a quiet lower back, not a big kick — if the back arches, the core has lost the fight.", how: ["Lie on your back. Residual supported and heavy on the bed.", "Lift the sound leg so the thigh is vertical, knee bent about 90°. Reach both arms straight up over the chest. This is the start.", "Press the lower back gently into the mat. Take a breath in. The ribs stay heavy.", "Breathe out. Lower the opposite arm overhead and the sound foot toward the floor, only as far as the back stays flat.", "Return to the start without letting the back arch. That is one rep.", "If the back lifts off the mat, shorten the movement. The residual can stay on the bed as an anchor — do not throw it to ‘match’ the sound side.", "Do not swing. Slow down. Quality over range."], adaptation: "Keep the low back quiet. Shorten the movement if it arches. Residual stays down unless your clinician has you lift it." },
  { id: "hamstring_stretch", name: "Hamstring stretch", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "seconds", defaultSets: 2, defaultValue: 20, source: SRC, cue: "On your back. Draw the sound leg up until you feel a stretch. Residual stays flat.", description: "A still stretch of the sound hamstring. BKA sheets also stretch the residual-side hip by keeping that limb flat while the other comes up. No bouncing.", how: ["Lie on your back. Residual flat and as straight as it will go — that is a hip stretch on that side.", "Lift the sound leg. Hold behind the thigh, not the knee.", "Straighten the sound knee until you feel a stretch in the back of the thigh. Pointing the toes toward the ceiling is enough; toward the floor makes it stronger.", "Hold. Breathe. Do not bounce. Switch the intent: then hug the residual toward the chest and push the sound leg flat, if that is in your programme."], adaptation: "Do not bounce. Stop on nerve-type shooting pain." },
  { id: "prone_elbows", name: "Prone on elbows", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "seconds", defaultSets: 2, defaultValue: 20, source: SRC, cue: "Lie on your front, propped on the elbows.", description: "A hold on the front of the body, propped on the elbows. Builds trunk endurance and is a step toward comfortable prone lying — the position that undoes a flexed hip.", how: ["Roll onto your front. Residual comfortable, small pillow under the hip if the end of the limb protests.", "Prop on the elbows. Shoulders stacked over the elbows, chest open.", "Breathe. Look slightly down so the neck is long.", "Come down if the residual throbs or the low back pinches."], adaptation: "Come down if the residual protests. A pillow under the stomach is fine at first." },
  { id: "hip_ext_arom", name: "Hip extension AROM", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 10, source: SRC, cue: "On your front. Lift the residual straight up. Hips stay on the bed.", description: "The staple BKA hip-extensor drill: lie on your stomach and lift the residual toward the ceiling with the knee straight. Alberta and Premier Surgical both say: squeeze the buttock, do not lift the hip bone off the bed, do not arch.", how: ["Lie on your front. Small pillow under the residual knee if the end of the limb is tender.", "Keep both hip bones on the bed.", "Lift the residual straight up, knee straight. Small lift. Hold about five seconds.", "Lower. The work is the buttock, not the low back."], adaptation: "Small lift. No low-back pinch. If you cannot lie on your front, use the side-lying ‘leg back’ version instead." },
  { id: "hip_ext_bent", name: "Hip extension, bent knee", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, cue: "On your stomach, residual knee bent. Lead with the residual and lift.", description: "Same hip-extensor lift with the residual knee bent. Bending the knee takes some hamstring out so the buttock has to do the lift — a common progression on BKA sheets.", how: ["Lie on your stomach. Bend the residual knee as much as is comfortable.", "Lead with the residual. Lift the thigh a little off the bed.", "Higher only if the hip bones stay down. Stop on sharp pain at the residual end."], adaptation: "Stop on sharp pain. Do not twist the pelvis." },
  { id: "bridge_sound", name: "Bridge, sound leg", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, cue: "On your back, sound foot flat. Residual on a towel. Lift the hips evenly.", description: "A bridge. Published programmes put a roll under the residual and the sound foot flat, then lift both hips the same amount. Twisting toward the residual is the cheat to watch.", how: ["Lie on your back. Sound foot flat, knee bent.", "Residual resting on a rolled towel so it can press down.", "Press through the sound heel and the residual. Lift the hips. Both sides the same height.", "Hold a breath’s length. Lower with control."], adaptation: "Press through the sound heel. If the residual cannot press, still keep that hip from dropping." },
  { id: "bridge_band", name: "Bridge, arms at side (band)", category: "bka", tag: "bka", equipment: ["loop_band", "mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, cue: "Light loop around the thighs. Sound foot flat. Lift the hips.", description: "Bridge with a light loop so the hip abductors work while you lift — the same muscles that stop a Trendelenburg dip on the sound leg later.", how: ["Light loop above the knees, or as low on the residual as is comfortable.", "Lie on your back. Sound foot flat. Arms at your sides.", "Press the knees gently out into the band. Then lift the hips.", "Lower. Light band first."], adaptation: "Light band first. Stop if residual skin rolls." },
  { id: "hip_abd_supine", name: "Hip abduction, on back", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 10, source: SRC, cue: "Flat on your back. Slide the residual out to the side. Kneecap faces the ceiling.", description: "The ‘snow angel’ slide on the Saskatchewan BKA sheet. Take the residual out to the side and back. The kneecap stays pointing up — if it rolls in or out, the hip is cheating.", how: ["Lie flat on your back. Residual as straight as it will go.", "Slide or lift the residual straight out to the side.", "Kneecap faces the ceiling the whole way. Pelvis stays still.", "Return."], adaptation: "Keep the pelvis still. A sock on the residual helps it slide on the sheet." },
  { id: "hip_abd_band_lie", name: "Hip abduction (band, lying)", category: "bka", tag: "bka", equipment: ["loop_band", "mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 10, source: SRC, cue: "Band around the thighs. On your back. Press the residual out.", description: "Same side-press as hip abduction, with a loop for load. Premier Surgical’s BKA programme uses a belt or band as low as is comfortable, then a five-count press.", how: ["Band on around both thighs, as low as is comfortable.", "Lie on your back.", "Press the residual out against the band. Hold a slow five. Relax.", "Stop if the residual skin rolls or pinches."], adaptation: "Stop if the residual skin rolls." },
  { id: "hip_add_iso", name: "Hip adduction isometric", category: "bka", tag: "bka", equipment: ["mat"], position: "seated", metric: "seconds", defaultSets: 3, defaultValue: 8, source: SRC, cue: "Towel between the thighs. Press the legs together. Hold.", description: "A gentle inner-thigh press. SGH and Saskatchewan both use a towel roll between the thighs, squeeze, hold about five seconds. Nothing needs to move.", how: ["Sit with the legs long, or lie on your back.", "Towel or pillow between the thighs, as low as is comfortable.", "Press the legs together. Hold. Gentle.", "Relax a few seconds. Repeat."], adaptation: "Gentle press. Do not twist the residual inward to cheat." },
  { id: "sidelying", name: "Sidelying", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "seconds", defaultSets: 2, defaultValue: 30, source: SRC, cue: "Lie on your side. Head supported. Residual comfortable.", description: "A rest position and the start position for the side-lying hip work. Comfort here matters — if the residual is crushed or hanging, the hip work that follows will be ugly.", how: ["Lie on your side. Head on a pillow. Body in a long line, not curled into a C.", "Residual in line with the trunk. Pillow between the limbs if the residual needs it.", "Breathe. Change sides when the hold is done."], adaptation: "Pillow between limbs if needed. Do not lie on a fresh incision." },
  { id: "hip_abd_arom", name: "Hip abduction AROM", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 10, source: SRC, cue: "Lie on the sound side. Lift the residual straight up. Knee faces forward.", description: "On your sound side, lift the residual toward the ceiling. Alberta: knee straight, residual in line with the body, not drifting forward. Do not roll onto your back as you lift.", how: ["Lie on the sound side. Sound hip and knee slightly bent for balance.", "Body in a straight line. Residual stacked above the sound limb.", "Lift the residual straight up. Knee faces forward, not the ceiling.", "Hold about five seconds. Lower slow. Stay on your side."], adaptation: "Do not roll the pelvis back. Smaller lift if you start to roll." },
  { id: "hip_flex_ext_arom", name: "Hip flexion + extension AROM", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, cue: "Lie on your side. Residual forward, then straight back. Stay on your side.", description: "On your side, send the residual forward, then press it straight back. SHA uses the ‘leg back’ part as the substitute if you cannot lie on your stomach. The backswing is the one that fights a flexed hip.", how: ["Lie on your side, body long.", "Send the residual forward, as if marching.", "Then press it straight back behind the body. Stay on your side. Do not roll.", "Slow. The backswing is small and high-quality, not a kick."], adaptation: "Slow. Stay on your side. Skip the backswing if the residual end is very tender — use prone lifts instead when you can." },
  { id: "prone_lying", name: "Prone lying", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "seconds", defaultSets: 1, defaultValue: 60, source: SRC, cue: "Lie on your front. Quiet breathing. Hips straight.", description: "A still lie on the front. Pre-prosthetic programmes put this near the top: 15–30 minutes twice a day, when you can, to stop the hip staying bent from sitting. Even a minute is worth logging if that is the dose in your plan.", how: ["Lie on your front. Head turned to a comfortable side.", "Hips flat. Residual relaxed. A small pillow under the residual or stomach if you need it.", "Quiet breathing. This is a stretch of the front of the hip, not a workout.", "Come off if the residual throbs or you cannot breathe easily."], adaptation: "Build the time. Come off if the residual throbs. A pillow under the chest is fine." },
  { id: "lie_to_sit", name: "Transfer, lie to sit", category: "bka", tag: "bka", equipment: ["mat"], position: "lying", metric: "reps", defaultSets: 2, defaultValue: 4, source: SRC, cue: "Roll to the side. Elbow. Press up with the arms to sit.", description: "The bed-to-sit transfer. Amputee physio treats this as a skill, not a sit-up: roll toward the edge, come onto an elbow, press to sitting, sound foot finding the floor.", how: ["Start on your back, a little toward the side you will sit off.", "Roll onto your side, facing the edge.", "Come up onto an elbow. Then the hand.", "Press up with the arms to sit. The sound side helps. Residual does not have to swing wildly.", "Pause sitting tall. Reverse to lie back down. That is one rep."], adaptation: "Use the sound side. Do this toward a clear floor, not into a wall." },
  { id: "chair_dip", name: "Chair dip", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "reps", defaultSets: 2, defaultValue: 6, source: SRC, cue: "Hands on the armrests. Press and lift the seat off the chair.", description: "Chair push-up from the Saskatchewan advanced set and Alberta’s chair press: brakes on if it is a wheelchair, chair against a wall otherwise. Press through the hands, lift the seat, hold a few seconds. Builds the arms used in every transfer.", how: ["Sit. Chair against a wall, or wheelchair brakes on.", "Hands on the armrests. Sound foot on the floor.", "Press and lift the seat off the chair. Elbows straighten.", "Hold about three seconds if you can. Lower with control."], adaptation: "Feet stay light. Skip if the shoulders complain. Do not do this on a chair with wheels that are not locked." },
  { id: "trunk_rot_seated", name: "Lower trunk rotation", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, cue: "Sit tall, arms crossed. Twist to one side, then the other.", description: "Seated twist. Arms crossed. The pelvis stays on the chair so the rotation comes from the trunk — the same control you need to reach a seatbelt or a bedside table without falling toward the residual.", how: ["Sit tall. Both sit-bones honest on the seat. Arms crossed.", "Twist to one side. Pause.", "Twist to the other. Pull a little further with the arms only if it stays easy."], adaptation: "Use the arms to pull a little further only if it stays easy. Residual does not hook the chair to cheat." },
  { id: "lateral_shift", name: "Lateral weight shift", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, cue: "Sit tall. Lean to one sit-bone, then the other.", description: "Shift weight from one sit-bone to the other without collapsing. After a BKA the habit is to park on the sound side. This drill makes both sides available before a stand.", how: ["Sit tall, feet or residual supported.", "Lean to one sit-bone. Pause. The opposite sit-bone gets light but you do not slump.", "Lean to the other. Keep the chest open."], adaptation: "Keep both sit-bones honest. Hold the chair if balance is poor." },
  { id: "chair_reach", name: "Balance, lateral reach", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, cue: "Sit in the chair. Reach to one side, then the other.", description: "A seated reach that challenges balance outside the base of support. Hold the chair if you need it. Useful before standing work.", how: ["Sit in the chair, a little away from the backrest if you can.", "Reach to one side, as if taking a cup from a table. Pause.", "Reach to the other. Hold the chair with the other hand if you need it."], adaptation: "Hold the chair if you need it. Do not reach so far that you slide off." },
  { id: "trunk_flex_stretch", name: "Trunk forward flexion stretch", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "seconds", defaultSets: 2, defaultValue: 20, source: SRC, cue: "Sit in the chair. Hang the trunk toward the ground. Come up slow.", description: "A forward hang from the chair. Lets the low back and the back of the sound thigh ease. Come up slow so the residual does not have to catch you.", how: ["Sit in the chair, sound foot on the floor.", "Hang the trunk toward the ground, arms heavy.", "Breathe. Come up slow, stacking the chest last."], adaptation: "Come up slow. Skip if you get dizzy hanging forward." },
  { id: "trunk_side_stretch", name: "Trunk side flexion stretch", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "seconds", defaultSets: 2, defaultValue: 15, source: SRC, cue: "Sit. Hang forward, then take the trunk to one side.", description: "Forward hang, then take it to one side. Change sides. The residual-side waist is often tight from sitting in a lean.", how: ["Sit in the chair.", "Hang forward, then to one side.", "Breathe. Change sides. No pain into the residual."], adaptation: "No pain into the residual. Hold the opposite armrest if you need a brake." },
  { id: "hip_flex_ext_stand", name: "Hip flexion + extension, supported", category: "bka", tag: "bka", equipment: ["chair"], position: "standing", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, cue: "Stand on the sound leg. Hold the chair. Residual forward, then straight back.", description: "Standing three-way hip, flexion and extension. Hold the chair. The sound leg is the stance leg — this is the strength that later lets you walk without dumping onto a walker. Residual swings forward, then straight back. Trunk stays tall.", how: ["Stand on the sound leg. Both hands on the chair back.", "Lift the residual forward, as if marching. Pause.", "Then swing it straight back. Small range. Stay tall.", "Do not lean the trunk to make the residual look busy."], adaptation: "Small range. Stay tall. Prosthesis off unless your clinician has you do this in the limb." },
  { id: "hip_abd_stand", name: "Hip abduction, supported", category: "bka", tag: "bka", equipment: ["chair"], position: "standing", metric: "reps", defaultSets: 2, defaultValue: 8, source: SRC, cue: "Stand on the sound leg. Hold the chair. Residual straight out to the side.", description: "Standing side-lift of the residual. Trunk stays upright. Leaning the chest away is the cheat — the hip abductor on the stance side is what should be working.", how: ["Stand on the sound leg. Hold the chair.", "Lift the residual straight out to the side. Kneecap faces forward.", "Do not lean the trunk away. Lower."], adaptation: "Do not lean the trunk away. Smaller lift is better than a lean." },
  { id: "sit_to_stand", name: "Sit to stand (table)", category: "bka", tag: "bka", equipment: ["chair"], position: "seated", metric: "reps", defaultSets: 2, defaultValue: 6, source: SRC, cue: "Scoot forward. Hands on the table. Lean, sound knee over toes, stand.", description: "The sit-to-stand from a chair using a table. Amputee transfer training: scoot forward, sound foot back under the knee, hands on the table, nose over toes, press to stand on the sound leg. Sit by reaching for the seat, not by collapsing.", how: ["Chair stable. Table in front. Scoot forward so you are on the front half of the seat.", "Sound foot back, under the knee. Residual comfortable, not tucked awkwardly.", "Hands on the table. Lean the trunk forward until the nose is over the toes.", "Press through the sound heel and the hands. Stand. Pause tall.", "To sit: feel the seat with the back of the sound leg, reach for the chair or table, sit with control. That is one rep."], adaptation: "Use the table. Sit back with control. Do not do this on wheels that are not locked." }
];

const SKIP = [
  { id: "pain", label: "Pain" },
  { id: "fatigue", label: "Fatigue" },
  { id: "no_kit", label: "No kit" },
  { id: "time", label: "No time" },
  { id: "other", label: "Other" }
];

const TUTORIAL = [
  { title: "Today", body: "This is home. Start a session on a training day, or skip and tell Cappie why. Night mode sits at the top so the screen is easy in the evening." },
  { title: "A session", body: "Each exercise has a plain-language how-to written for residual and sound sides, a timer, and set counters. Read What needs to happen, then mark a set done when you finish it." },
  { title: "Plan", body: "Turn exercises on or off. Change sets and reps. Below-knee unlocks the chair and mat programme." },
  { title: "Stats", body: "See how many exercises you logged each day, and whether each movement improved or declined over the week or month." },
  { title: "Settings", body: "Theme, wallpaper, one-handed mode, and this tutorial live here. The period in Cappie. follows the theme colour. Changes save on this phone and to your cloud account." },
  {
    title: "On your Home Screen",
    body: "Add Cappie so it opens like any other app — full screen, with the mountain icon. Safari on iPhone, Chrome on Android.",
    steps: [
      "iPhone: open this page in Safari (Chrome cannot add it). Tap Share — the square with the arrow. Scroll and tap Add to Home Screen. Tap Add.",
      "Android: open this page in Chrome. Tap the three-dot menu. Tap Add to Home screen or Install app. Tap Add."
    ]
  }
];

export { KEY, DAYS, LIMB_OPTIONS, EQUIPMENT_OPTIONS, THEMES, WALLS, EXERCISES, SKIP, TUTORIAL };
